// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7CKvRhgF35TEOLE1sr35k8BNHwYzIPUY',
    appId: '1:31888991447:web:eb38bbfab7824777f33c92',
    messagingSenderId: '31888991447',
    projectId: 'palma-database',
    authDomain: 'palma-database.firebaseapp.com',
    storageBucket: 'palma-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYd5HVqdS4yXVhdk0QIsfg2bpSIPI9Eeg',
    appId: '1:31888991447:android:4fbd6fc7ee57d68cf33c92',
    messagingSenderId: '31888991447',
    projectId: 'palma-database',
    storageBucket: 'palma-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5P2BIO3uL2HTlCIBkVGYqPodtgYONeA0',
    appId: '1:31888991447:ios:8af7e36e0e497ce0f33c92',
    messagingSenderId: '31888991447',
    projectId: 'palma-database',
    storageBucket: 'palma-database.appspot.com',
    iosBundleId: 'com.example.palmDeseas',
  );
}
